import { Text, View } from "../../components/themed";

export default () => {
  return (
    <View>
      <Text>
        CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS
        CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS
        CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS
        CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS
        CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS CARDS
      </Text>
    </View>
  );
};
